apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: rukpak-system
  name: core
  labels:
    app: core
spec:
  template:
    metadata:
      annotations:
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
    spec:
      priorityClassName: system-cluster-critical
