---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rukpak-webhooks-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rukpak-webhooks-admin
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: rukpak-webhooks-admin
    namespace: openshift-rukpak
