---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: helm-provisioner-cert
  name: helm-provisioner
  namespace: openshift-rukpak
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app: helm-provisioner
