---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: rukpak-webhook-certificate
  name: rukpak-webhook-service
  namespace: openshift-rukpak
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    app: webhooks
